"""
deploy.py — Model Deployment Script
Generated by ML Engineer Agent — SAST approved
"""
import os, joblib, pandas as pd
from pathlib import Path

MODEL_PATH = os.getenv("MODEL_PATH", "model/model.joblib")

def load_model():
    path = Path(os.path.realpath(os.path.abspath(MODEL_PATH)))
    if not path.exists():
        raise FileNotFoundError(f"Model not found: {path}")
    return joblib.load(path)

def predict(features: dict) -> dict:
    if not features:
        raise ValueError("features dict cannot be empty")
    model = load_model()
    df = pd.DataFrame([features])
    return {
        "prediction":  bool(model.predict(df)[0]),
        "probability": round(float(model.predict_proba(df)[0][1]), 4),
    }

if __name__ == "__main__":
    print(predict({"account_age": 2.4, "session_duration": 1.8}))
