"""
pipeline.py — ML Pipeline (fraud detection)
Generated by ML Engineer Agent
Recommendations applied from data_scientist/eda_report.md
"""
import os, pandas as pd, numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score
import joblib
from pathlib import Path

DB_CONN_STR = os.getenv("DB_CONN_STR")
MODEL_PATH  = Path(os.path.abspath(os.getenv("MODEL_PATH", "model/model.joblib")))
DATA_PATH   = Path(os.path.abspath(os.getenv("DATA_PATH",  "data/dataset.csv")))

def load_data(path):
    df = pd.read_csv(path)
    print(f"Loaded: {df.shape[0]} rows x {df.shape[1]} cols")
    return df

def preprocess(df):
    # Recommendations applied from data_scientist/eda_report.md
    drop_cols = ['promo_clicks', 'referral_code']
    df = df.drop(columns=[c for c in drop_cols if c in df.columns])
    for col in ['account_age`:', 'session_duration`:', 'log1p(account_age', 'log1p(session_duration']:
        if col in df.columns: df[col] = np.log1p(df[col])
    for col in ['one-hot(device_type']:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
            df = pd.concat([df.drop(col, axis=1), dummies], axis=1)
    X = df.drop(df.columns[-1], axis=1)
    y = df.iloc[:, -1]
    return train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

def train(X_train, y_train):
    return RandomForestClassifier(
        n_estimators=200, max_depth=12,
        class_weight='balanced', random_state=42, n_jobs=-1
    ).fit(X_train, y_train)

def evaluate(model, X_test, y_test):
    yp = model.predict(X_test)
    ypr = model.predict_proba(X_test)[:,1]
    return {
        "accuracy": round(accuracy_score(y_test, yp), 4),
        "f1":       round(f1_score(y_test, yp), 4),
        "auc":      round(roc_auc_score(y_test, ypr), 4),
    }

if __name__ == "__main__":
    df = load_data(DATA_PATH)
    X_train, X_test, y_train, y_test = preprocess(df)
    model = train(X_train, y_train)
    metrics = evaluate(model, X_test, y_test)
    MODEL_PATH.parent.mkdir(parents=True, exist_ok=True)
    joblib.dump(model, str(MODEL_PATH))
    print("Done:", metrics)
