// src/Dashboard.jsx — Project Frontend
// Generated by Frontend Agent — connects to project prediction API at http://localhost:5050
// Run: npm install && npm run dev  →  opens http://localhost:3000
import React, { useState, useEffect } from "react";
import DOMPurify from "dompurify";

  const API_BASE = import.meta.env.VITE_API_URL || "http://localhost:5050";

export default function Dashboard() {
  const [metrics,    setMetrics]    = useState(null);
  const [prediction, setPrediction] = useState(null);
  const [health,     setHealth]     = useState(null);
  const [error,      setError]      = useState(null);
  const [loading,    setLoading]    = useState(true);
  const [predLoading,setPredLoading]= useState(false);

  useEffect(() => {
    Promise.all([
      fetch(`${API_BASE}/health`).then(r => r.json()).catch(() => null),
      fetch(`${API_BASE}/metrics`).then(r => r.json()).catch(() => null),
    ]).then(([h, m]) => {
      setHealth(h);
      setMetrics(m);
      setLoading(false);
    });
  }, []);

  const runPrediction = () => {
    setPredLoading(true);
    fetch(`${API_BASE}/predict`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ account_age: 24, session_duration: 5.2 }),
    })
      .then(r => r.json())
      .then(data => { setPrediction(data); setPredLoading(false); })
      .catch(e  => { setError(e.message);  setPredLoading(false); });
  };

  if (loading) return <div style={{padding:32}}>Connecting to backend at {API_BASE}...</div>;

  return (
    <div style={{ fontFamily: "sans-serif", padding: 32, maxWidth: 900, margin: "0 auto" }}>
      <h1>Model Dashboard</h1>

      {/* Backend status */}
      <div style={{ marginBottom: 16 }}>
        <span style={{ background: health?.status === "ok" ? "#22c55e" : "#ef4444",
                        color: "#fff", padding: "4px 12px", borderRadius: 99, fontSize: 13 }}>
          Backend {health?.status === "ok" ? "✅ Connected" : "❌ Offline"}
        </span>
        {health?.project && (
          <span style={{ marginLeft: 12, color: "#6b7280", fontSize: 13 }}>
            Project: {DOMPurify.sanitize(health.project)}
          </span>
        )}
      </div>

      {/* Metrics grid */}
      {metrics && (
        <div style={{ display: "grid", gridTemplateColumns: "repeat(3,1fr)", gap: 16, marginBottom: 24 }}>
          <MetricCard label="Accuracy"    value={`${metrics.accuracy}%`}       />
          <MetricCard label="F1 Score"    value={String(metrics.f1)}             />
          <MetricCard label="AUC"         value={String(metrics.auc)}            />
          <MetricCard label="Drift Score" value={String(metrics.drift_score)}    />
          <MetricCard label="Latency p95" value={`${metrics.latency_p95}ms`}   />
          <MetricCard label="Volume"      value={metrics.inference_volume?.toLocaleString()} />
        </div>
      )}

      {/* Live prediction */}
      <div style={{ border: "1px solid #e5e7eb", borderRadius: 8, padding: 20 }}>
        <h3 style={{ margin: "0 0 12px" }}>Live Prediction Test</h3>
        <p style={{ color: "#6b7280", margin: "0 0 12px", fontSize: 13 }}>
          Payload: {{ account_age: 24, session_duration: 5.2 }}
        </p>
        <button
          onClick={runPrediction}
          disabled={predLoading}
          style={{ background: "#3b82f6", color: "#fff", border: "none",
                    padding: "8px 20px", borderRadius: 6, cursor: "pointer" }}
        >
          {predLoading ? "Running..." : "POST /predict"}
        </button>

        {prediction && (
          <div style={{ marginTop: 16, background: "#f0fdf4", padding: 16, borderRadius: 6 }}>
            <strong>Response from {API_BASE}/predict:</strong>
            <pre style={{ margin: "8px 0 0", fontSize: 13 }}>
              {DOMPurify.sanitize(JSON.stringify(prediction, null, 2))}
            </pre>
          </div>
        )}
        {error && (
          <div style={{ marginTop: 12, color: "#ef4444", fontSize: 13 }}>
            Error: {DOMPurify.sanitize(error)}
          </div>
        )}
      </div>
    </div>
  );
}

function MetricCard({ label, value }) {
  return (
    <div style={{ border: "1px solid #e5e7eb", borderRadius: 8, padding: 16 }}>
      <div style={{ color: "#6b7280", fontSize: 12, marginBottom: 4 }}>
        {DOMPurify.sanitize(label)}
      </div>
      <div style={{ fontSize: 24, fontWeight: 600 }}>
        {DOMPurify.sanitize(String(value ?? "—"))}
      </div>
    </div>
  );
}
