"""
feature_engineering.py
Generated by Data Scientist Agent — derived from eda_report.md
"""
import numpy as np
import pandas as pd


DROP_COLS    = ['promo_clicks', 'referral_code']
LOG_COLS     = ['account_age`:', 'session_duration`:', 'log1p(account_age', 'log1p(session_duration']
ENCODE_COLS  = ['one-hot(device_type']


def engineer_features(df: pd.DataFrame) -> pd.DataFrame:
    """Apply all EDA-recommended transforms (sourced from eda_report.md)."""
    df = df.copy()
    df.drop(columns=[c for c in DROP_COLS if c in df.columns], inplace=True)
    for col in LOG_COLS:
        if col in df.columns:
            df[col] = np.log1p(df[col])
    for col in ENCODE_COLS:
        if col in df.columns:
            dummies = pd.get_dummies(df[col], prefix=col, drop_first=True)
            df = pd.concat([df.drop(col, axis=1), dummies], axis=1)
    return df
